language: go
go_import_path: github.com/derailed/popeye
go:
  - "1.12"
  # - master

os:
  - linux
  - osx

dist: trusty
sudo: false

install: true

env:
  - GO111MODULE=on

script:
  - go build
  - go test ./...
